eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
server:
  port: 8762
spring:
  application:
    name: zuul-server
zuul:
  ignored-services: '*'
  routes:
    movie-client:
      path: /movie/**
      service-id: movie-client
    recommendation-client:
      path: /recommendation/**
      service-id: recommendation-client
