server:
  port: 8040
eureka:  client:    serviceUrl:      defaultZone: http://localhost:8761/eureka/
spring:  h2:    console:      path: /console
      enabled: true
      settings:        web-allow-others: true
  application:    name: recommendation-client             