server:
  port: 8070
spring:  application:    name: product-service  data:    mongodb:      host: localhost
      port: 27017
      database: product  boot:    admin:      client:        url: http://localhost:9000
     
eureka:  client:    serviceUrl:      defaultZone: http://localhost:8761/eureka/
management:  endpoints:    web:      exposure:        include: '*'