server:
  port: 8090
eureka:  client:    service-url:      defaultZone: http://localhost:8761/eureka/
spring:              
  datasource:
    url: jdbc:mysql://localhost:3306/springuser
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: welcome